### ISSUE TITLE
fedora:36 peculiarities

### ISSUE THREAD

**Issue by andyholmes** [GSConnect/gsconnect-ci#5]
In the case there is time/interest in bumping the CI image to `fedora:36`, it will require a patched GLib to address [this issue](https://gitlab.gnome.org/Infrastructure/GitLab/-/issues/545). Long story short, is that `glib-compile-resources` will fail until GitHub updates their Docker/libseccomp deployment.

I have a copr setup [here](https://copr.fedorainfracloud.org/coprs/andyholmes/main/packages/) that carries such a build of GLib. It could be added to the Dockerfile like so:

```Dockerfile
FROM registry.fedoraproject.org/fedora:36

# See: https://github.com/andyholmes/copr/tree/main/glib2
RUN dnf install -y 'dnf-command(copr)' && \
    dnf copr -y enable andyholmes/main

# Regular stuff here
```

**Comment by ferdnyc** [comment]
Fedora 36 isn't even technically in Beta yet. (Been pushed off for two weeks and counting, so far, though it looks like the [Big Board](https://qa.fedoraproject.org/blockerbugs/milestone/36/beta/buglist) has been cleared so this Thursday's third try will probably succeed...)

Since this was [patched a month ago](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2435) I can't imagine it won't make it into the release. I'd be surprised if it's not in the Beta (or I'd expect to see it on the Big Board).

Point is, we can probably solve this by just doing nothing for a few weeks. My favorite kind of fix!

**Comment by ferdnyc** [comment]
And, indeed, that patch has already been [pushed as an update to Fedora 35](https://src.fedoraproject.org/rpms/glib2/pull-request/12), even. For Fedora 36+, BNocera dropped it in as a patch [around the same time](https://src.fedoraproject.org/rpms/glib2/c/12966f03f4988b5194db244917a03ba46f602668?branch=rawhide), but it's no longer there since that was [four releases ago](https://src.fedoraproject.org/rpms/glib2/commits/rawhide) and the current packages are up to 2.72.0 already which includes the patch upstream.

The Dockerhub definition for `fedora:36`  [was updated end of last week](https://github.com/fedora-cloud/docker-brew-fedora/blob/7190c545d2f9f0f7e54d6d972fc84621a83c1ad4/x86_64/Dockerfile); if this isn't already fixed something's wrong.

**Comment by andyholmes** [comment]
Yeah, I'm not sure if they'll forward-port the EPERM patch again. Richard Hughsie had pushed that since he uses GitHub/Circle CI for `fwupd`, but I get the feeling Fedora doesn't want to carry that patch as it was causing timeouts in the GNOME GitLab CI's.

**Comment by andyholmes** [comment]
Sorry, after re-reading your comment I think I didn't explain very well.

Philip Withnall merged [this patch](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2435) late in the `2.70` cycle for seccomp deployments that return `EPERM` for `close_range()` rather than `ENOSYS`, which resulted in dangling file descriptors (causing many problems in GNOME's GitLab runners).

After it became clear this was breaking a lot of GitHub-based CI's, Richard Hughsie added [this patch](https://src.fedoraproject.org/rpms/glib2/blob/f35/f/gspawn-eperm.patch) to the Fedora 35 GLib package, which effectively reverts Philip Withnall's upstream patch.

So far, Richard Hughsie's patch has not been applied to Fedora 36's GLib package though, thus bumping the CI image to `fedora:36` will break it. I don't get the feeling Fedora plans on carrying Richard's patch again, like they did for Fedora 35.

**Comment by ferdnyc** [comment]
@andyholmes 

Ah, OK, thanks. I guess I understand better now why it's needed. Well, no, I understand _what_ it's needed _for_, but I don't **at all** understand WHY it's needed. Especially with all of the bugs on this being closed and everyone walking around acting as though this is fixed.

Do the Fedora devs know that they're currently working towards a release that will include tools that fail to run in container environments, in a way that those same tools on F35 (by virtue of that patch) and earlier DON'T? I find it hard to believe that this wouldn't be on the radar as a release blocker, but I can't even find any sign that it's being tracked anywhere (as an ongoing, rather than already-solved, problem, I mean).

**Comment by andyholmes** [comment]
@ferdnyc 

Yeah, my understanding of this stuff is pretty limited. My read is that `EPERM` is supposed to be returned when you try to do some thing seccomp doesn't allow (ie. hard fail). `ENOSYS` is returned when syscall is not supported (ie. time to fallback to an older syscall).

So I think the fix merged into GLib makes it correctly handle those error codes, but some existing deployments like GitHub's are still returning `EPERM` when they should be returning `ENOSYS`. The practical difference is that GNOME can update their Docker/seccomp deployment on gitlab.gnome.org, while we on GitHub are stuck with a Docker/seccomp that is returning the wrong error code.

That's my read on the situation anyways :)

**Comment by andyholmes** [comment]
Looks like [this made it in](https://src.fedoraproject.org/rpms/glib2/blob/f36/f/gspawn-eperm.patch) afterall, so I'll close this up :)
